CREATE TABLE v1_brands (brand_id VARCHAR(128) PRIMARY KEY, tenant_id VARCHAR(128) NOT NULL);
CREATE INDEX brands_tenant ON v1_brands (tenant_id);
ALTER TABLE audit_log ADD COLUMN sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX audit_chain_order ON audit_log (tenant_id, brand_id, sequence);
